import { jsPDF } from "jspdf";

const MARGIN = 48;
const PAGE_WIDTH = 595; // A4 pt width

function addWrappedText(doc: jsPDF, text: string, y: number, fontSize = 10): number {
  doc.setFontSize(fontSize);
  const lines = doc.splitTextToSize(text, PAGE_WIDTH - MARGIN * 2);
  for (const line of lines) {
    if (y > 780) {
      doc.addPage();
      y = MARGIN;
    }
    doc.text(line, MARGIN, y);
    y += fontSize * 1.5;
  }
  return y + 8;
}

function addHeading(doc: jsPDF, text: string, y: number): number {
  if (y > 760) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(29, 78, 216); // royal blue
  doc.text(text, MARGIN, y);
  doc.setTextColor(10, 15, 44); // navy
  doc.setFont("helvetica", "normal");
  return y + 22;
}

export function exportBusinessPlanPDF(plan: {
  inputs: { businessName: string };
  executiveSummary: string;
  businessPlan: string;
  swot: { strengths: string[]; weaknesses: string[]; opportunities: string[]; threats: string[] };
  canvas: Record<string, string>;
  financialProjection: { year: string; revenue: string; costs: string; profit: string }[];
  marketingSummary: string;
  legalChecklist: string[];
  startupChecklist: string[];
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(10, 15, 44);
  doc.text(plan.inputs.businessName || "Business Plan", MARGIN, y);
  y += 14;
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by VentureOS", MARGIN, y);
  doc.setTextColor(10, 15, 44);
  y += 30;

  y = addHeading(doc, "Executive Summary", y);
  y = addWrappedText(doc, plan.executiveSummary, y);

  y = addHeading(doc, "Business Plan", y);
  y = addWrappedText(doc, plan.businessPlan.replace(/##\s*/g, ""), y);

  y = addHeading(doc, "SWOT Analysis", y);
  y = addWrappedText(doc, "Strengths: " + plan.swot.strengths.join("; "), y);
  y = addWrappedText(doc, "Weaknesses: " + plan.swot.weaknesses.join("; "), y);
  y = addWrappedText(doc, "Opportunities: " + plan.swot.opportunities.join("; "), y);
  y = addWrappedText(doc, "Threats: " + plan.swot.threats.join("; "), y);

  y = addHeading(doc, "Business Model Canvas", y);
  for (const [key, value] of Object.entries(plan.canvas)) {
    y = addWrappedText(doc, `${key}: ${value}`, y);
  }

  y = addHeading(doc, "Financial Projection", y);
  for (const row of plan.financialProjection) {
    y = addWrappedText(doc, `${row.year} — Revenue: ${row.revenue}, Costs: ${row.costs}, Profit: ${row.profit}`, y);
  }

  y = addHeading(doc, "Marketing Summary", y);
  y = addWrappedText(doc, plan.marketingSummary, y);

  y = addHeading(doc, "Legal Checklist", y);
  y = addWrappedText(doc, plan.legalChecklist.map((i) => `• ${i}`).join("\n"), y);

  y = addHeading(doc, "Startup Checklist", y);
  y = addWrappedText(doc, plan.startupChecklist.map((i) => `• ${i}`).join("\n"), y);

  doc.save(`${(plan.inputs.businessName || "business-plan").replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

export function exportMarketingPlaybookPDF(plan: {
  inputs: { businessName: string };
  contentCalendar: { day: number; theme: string; platform: string; idea: string }[];
  instagramStrategy: string;
  tiktokStrategy: string;
  linkedinStrategy: string;
  emailCampaign: string[];
  launchPlan: string[];
  salesFunnel: { stage: string; action: string }[];
  seoPlan: string[];
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(10, 15, 44);
  doc.text(`${plan.inputs.businessName || "Marketing Playbook"} — Marketing Playbook`, MARGIN, y);
  y += 30;

  y = addHeading(doc, "30-Day Content Calendar", y);
  for (const day of plan.contentCalendar) {
    y = addWrappedText(doc, `Day ${day.day} (${day.platform}) — ${day.idea}`, y, 9);
  }

  y = addHeading(doc, "Instagram Strategy", y);
  y = addWrappedText(doc, plan.instagramStrategy, y);

  y = addHeading(doc, "TikTok Strategy", y);
  y = addWrappedText(doc, plan.tiktokStrategy, y);

  y = addHeading(doc, "LinkedIn Strategy", y);
  y = addWrappedText(doc, plan.linkedinStrategy, y);

  y = addHeading(doc, "Email Campaign", y);
  y = addWrappedText(doc, plan.emailCampaign.map((i, idx) => `${idx + 1}. ${i}`).join("\n"), y);

  y = addHeading(doc, "Launch Plan", y);
  y = addWrappedText(doc, plan.launchPlan.map((i) => `• ${i}`).join("\n"), y);

  y = addHeading(doc, "Sales Funnel", y);
  for (const stage of plan.salesFunnel) {
    y = addWrappedText(doc, `${stage.stage}: ${stage.action}`, y);
  }

  y = addHeading(doc, "SEO Plan", y);
  y = addWrappedText(doc, plan.seoPlan.map((i) => `• ${i}`).join("\n"), y);

  doc.save(`${(plan.inputs.businessName || "marketing-playbook").replace(/\s+/g, "-").toLowerCase()}-marketing.pdf`);
}
